# CPU Training Configuration for RetinexFormer on LOL v1
# Optimized for CPU training with smaller batch sizes and fewer workers

name: Enhancement_RetinexFormer_LOL_v1_CPU
model_type: ImageCleanModel
scale: 1
num_gpu: 0  # CPU mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: data/LOLv1/Train/target
    dataroot_lq: data/LOLv1/Train/input
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader - optimized for CPU
    use_shuffle: true
    num_worker_per_gpu: 2  # Reduced for CPU
    batch_size_per_gpu: 2  # Smaller batch size for CPU

    ### ------- Training on single fixed-patch size 64x64 (smaller for CPU)---------
    mini_batch_sizes: [2]   
    iters: [50000]  # Reduced iterations for testing
    gt_size: 64     # Smaller patches for CPU
    gt_sizes: [64]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: cpu  # Use CPU prefetching

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: data/LOLv1/Test/target
    dataroot_lq: data/LOLv1/Test/input
    io_backend:
      type: disk

# network structures
network_g:
  type: RetinexFormer
  in_channels: 3
  out_channels: 3
  n_feat: 40
  stage: 1
  num_blocks: [1,2,2]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  experiments_root: experiments/LOL_v1_CPU
  models: experiments/LOL_v1_CPU/models
  training_states: experiments/LOL_v1_CPU/training_states
  log: experiments/LOL_v1_CPU
  visualization: experiments/LOL_v1_CPU/visualization

# training settings
train:
  total_iter: 50000  # Reduced for CPU training
  warmup_iter: -1
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [20000, 30000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: false  # Disable for faster CPU training
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 1e-4  # Slightly lower learning rate
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 4
  val_freq: !!float 5e3  # Validate less frequently
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 2

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100  # Log more frequently to see progress
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~  # Disable wandb
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
